[package]
name = "cwg_2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#gilrs = "0.9.0"
macroquad = "0.3"
macroquad-canvas = "0.3.0"